import { LegalSourceRegistryItem } from './types.ts';

/**
 * REGISTRO PERSISTENTE DE FONTES OFICIAIS DO PODER JUDICIÁRIO BRASILEIRO
 *
 * Princípio: Todo conector aponta para documentação oficial e URL pública verificável.
 * Nenhum tribunal é declarado "CONNECTED" sem uma integração real executada e auditável.
 */

export const INITIAL_LEGAL_SOURCE_REGISTRY: LegalSourceRegistryItem[] = [
  // 1. FONTES DE PRECEDENTES QUALIFICADOS E DADOS ABERTOS (AUTOMATIZADAS NO MVP)
  {
    sourceId: 'stj-dados-abertos',
    name: 'Superior Tribunal de Justiça - Portal de Dados Abertos (SCON/CKAN)',
    courtCode: 'STJ',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_OPEN_DATA',
    officialBaseUrl: 'https://dadosabertos.web.stj.jus.br/',
    documentationUrl: 'https://dadosabertos.web.stj.jus.br/dataset',
    connectorStatus: 'READY',
    coverageStatus: 'Acórdãos publicados no DJe e repositório de decisões terminativas',
    verificationMethod: 'OPEN_DATA_DIGEST',
    termsStatus: 'COMPLIANT_PUBLIC_ACCESS',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: true,
    reviewedBy: 'Comitê Técnico Forense / JurisFlow',
    reviewedAt: '2026-09-18T08:00:00Z',
  },
  {
    sourceId: 'cnj-datajud',
    name: 'Conselho Nacional de Justiça - DataJud (API Pública Processual)',
    courtCode: 'CNJ',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_API',
    officialBaseUrl: 'https://api-publica.datajud.cnj.jus.br/',
    documentationUrl: 'https://datajud-wiki.cnj.jus.br/api-publica/',
    connectorStatus: 'READY',
    coverageStatus: 'Metadados processuais (capa, classe, órgão julgador, movimentos e TPU)',
    verificationMethod: 'AUTOMATED_API',
    termsStatus: 'COMPLIANT_PUBLIC_ACCESS',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: true,
    credentialConfigured: true, // Chave pública de homologação do CNJ pré-configurada
    reviewedBy: 'Comitê Técnico Forense / JurisFlow',
    reviewedAt: '2026-09-18T08:00:00Z',
  },
  {
    sourceId: 'cnj-bnp-pangea',
    name: 'Banco Nacional de Precedentes (BNP / Pangea - Justiça 4.0)',
    courtCode: 'BNP',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_API',
    officialBaseUrl: 'https://bnp.pdpj.jus.br/',
    documentationUrl: 'https://www.cnj.jus.br/tecnologia-da-informacao-e-comunicacao/justica-4-0/banco-nacional-de-precedentes-bnp/',
    connectorStatus: 'READY',
    coverageStatus: 'Temas Repetitivos, Repercussão Geral, IRDR, IAC e Súmulas Vinculantes',
    verificationMethod: 'AUTOMATED_API',
    termsStatus: 'COMPLIANT_PUBLIC_ACCESS',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: true,
    reviewedBy: 'Comitê Técnico Forense / JurisFlow',
    reviewedAt: '2026-09-18T08:00:00Z',
  },

  // 2. TRIBUNAIS SUPERIORES (CONSULTA OFICIAL E DADOS ABERTOS)
  {
    sourceId: 'stf-jurisprudencia',
    name: 'Supremo Tribunal Federal - Pesquisa de Jurisprudência & Corte Aberta',
    courtCode: 'STF',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://portal.stf.jus.br/jurisprudencia/',
    documentationUrl: 'https://portal.stf.jus.br/hotsites/corteaberta/',
    connectorStatus: 'READY',
    coverageStatus: 'Súmulas Vinculantes e Acórdãos com link oficial direto de inteiro teor',
    verificationMethod: 'OPEN_DATA_DIGEST',
    termsStatus: 'COMPLIANT_PUBLIC_ACCESS',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: true,
    reviewedBy: 'Equipe de Curadoria Forense',
    reviewedAt: '2026-09-18T08:00:00Z',
  },
  {
    sourceId: 'tst-jurisprudencia',
    name: 'Tribunal Superior do Trabalho - Consulta Unificada de Jurisprudência',
    courtCode: 'TST',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://www.tst.jus.br/jurisprudencia',
    documentationUrl: 'https://www.tst.jus.br/jurisprudencia',
    connectorStatus: 'READY',
    coverageStatus: 'Súmulas, OJs, Precedentes Normativos e Recursos de Revista Repetitivos',
    verificationMethod: 'OPEN_DATA_DIGEST',
    termsStatus: 'COMPLIANT_PUBLIC_ACCESS',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: true,
    reviewedBy: 'Equipe de Curadoria Forense',
    reviewedAt: '2026-09-18T08:00:00Z',
  },
  {
    sourceId: 'tse-jurisprudencia',
    name: 'Tribunal Superior Eleitoral - Jurisprudência & Súmulas',
    courtCode: 'TSE',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://www.tse.jus.br/jurisprudencia',
    documentationUrl: 'https://www.tse.jus.br/jurisprudencia',
    connectorStatus: 'MANUAL_ONLY',
    coverageStatus: 'Matéria eleitoral especializada - Link oficial para conferência humana',
    verificationMethod: 'HUMAN_VERIFICATION_LINK',
    termsStatus: 'MANUAL_ONLY',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  },
  {
    sourceId: 'stm-jurisprudencia',
    name: 'Superior Tribunal Militar - Jurisprudência Militar da União',
    courtCode: 'STM',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://www.stm.jus.br/jurisprudencia',
    documentationUrl: 'https://www.stm.jus.br/jurisprudencia',
    connectorStatus: 'MANUAL_ONLY',
    coverageStatus: 'Justiça Militar Federal - Link oficial para conferência humana',
    verificationMethod: 'HUMAN_VERIFICATION_LINK',
    termsStatus: 'MANUAL_ONLY',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  },

  // 3. JUSTIÇA FEDERAL (TRF1 A TRF6)
  ...([1, 2, 3, 4, 5, 6].map((region) => ({
    sourceId: `trf${region}-jurisprudencia`,
    name: `Tribunal Regional Federal da ${region}ª Região (TRF${region})`,
    courtCode: `TRF${region}`,
    jurisdiction: `TRF${region}`,
    sourceType: 'MANUAL_VERIFICATION_ONLY' as const,
    officialBaseUrl: `https://www.trf${region}.jus.br/`,
    documentationUrl: `https://www.trf${region}.jus.br/jurisprudencia`,
    connectorStatus: 'MANUAL_ONLY' as const,
    coverageStatus: 'Jurisprudência Regional Federal - Conferência Humana Obrigatória',
    verificationMethod: 'HUMAN_VERIFICATION_LINK' as const,
    termsStatus: 'MANUAL_ONLY' as const,
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  }))),

  // 4. JUSTIÇA DO TRABALHO (TRT1 A TRT24)
  ...([
    { region: 1, name: 'TRT1 (Rio de Janeiro)', url: 'https://www.trt1.jus.br/' },
    { region: 2, name: 'TRT2 (São Paulo Capital/Litoral)', url: 'https://ww2.trtsp.jus.br/' },
    { region: 3, name: 'TRT3 (Minas Gerais)', url: 'https://portal.trt3.jus.br/' },
    { region: 4, name: 'TRT4 (Rio Grande do Sul)', url: 'https://www.trt4.jus.br/' },
    { region: 15, name: 'TRT15 (Campinas / SP Interior)', url: 'https://trt15.jus.br/' },
  ].map((item) => ({
    sourceId: `trt${item.region}-jurisprudencia`,
    name: item.name,
    courtCode: `TRT${item.region}`,
    jurisdiction: `TRT${item.region}`,
    sourceType: 'MANUAL_VERIFICATION_ONLY' as const,
    officialBaseUrl: item.url,
    documentationUrl: `${item.url}jurisprudencia`,
    connectorStatus: 'MANUAL_ONLY' as const,
    coverageStatus: 'Jurisprudência Regional Trabalhista - Conferência Humana Obrigatória',
    verificationMethod: 'HUMAN_VERIFICATION_LINK' as const,
    termsStatus: 'MANUAL_ONLY' as const,
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  }))),

  // 5. TRIBUNAIS DE JUSTIÇA ESTADUAIS (AMOSTRA REPRESENTATIVA E LINKS OFICIAIS)
  ...([
    { code: 'TJSP', name: 'Tribunal de Justiça de São Paulo', url: 'https://esaj.tjsp.jus.br/cjsg/' },
    { code: 'TJRJ', name: 'Tribunal de Justiça do Rio de Janeiro', url: 'http://www.tjrj.jus.br/jurisprudencia' },
    { code: 'TJMG', name: 'Tribunal de Justiça de Minas Gerais', url: 'https://www.tjmg.jus.br/jurisprudencia/' },
    { code: 'TJRS', name: 'Tribunal de Justiça do Rio Grande do Sul', url: 'https://www.tjrs.jus.br/novo/jurisprudencia/' },
    { code: 'TJPR', name: 'Tribunal de Justiça do Paraná', url: 'https://www.tjpr.jus.br/jurisprudencia' },
    { code: 'TJSC', name: 'Tribunal de Justiça de Santa Catarina', url: 'https://www.tjsc.jus.br/jurisprudencia' },
    { code: 'TJBA', name: 'Tribunal de Justiça da Bahia', url: 'https://www.tjba.jus.br/' },
    { code: 'TJDFT', name: 'Tribunal de Justiça do Distrito Federal e Territórios', url: 'https://pesquisajurisprudencia.tjdft.jus.br/' },
  ].map((tj) => ({
    sourceId: `${tj.code.toLowerCase()}-jurisprudencia`,
    name: `${tj.name} (${tj.code})`,
    courtCode: tj.code,
    jurisdiction: tj.code.replace('TJ', ''),
    sourceType: 'MANUAL_VERIFICATION_ONLY' as const,
    officialBaseUrl: tj.url,
    documentationUrl: tj.url,
    connectorStatus: 'MANUAL_ONLY' as const,
    coverageStatus: 'Justiça Estadual Comum - Consulta pública via e-SAJ/Projudi (Conferência Humana Obrigatória)',
    verificationMethod: 'HUMAN_VERIFICATION_LINK' as const,
    termsStatus: 'MANUAL_ONLY' as const,
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  }))),

  // 6. ÓRGÃOS ADMINISTRATIVOS E TURMAS RECURSAIS
  {
    sourceId: 'tnu-jurisprudencia',
    name: 'Turma Nacional de Uniformização dos JEFs (TNU / CJF)',
    courtCode: 'TNU',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://www.cjf.jus.br/cjf/jurisprudencia/turma-nacional-de-uniformizacao',
    documentationUrl: 'https://www.cjf.jus.br/cjf/jurisprudencia/turma-nacional-de-uniformizacao',
    connectorStatus: 'MANUAL_ONLY',
    coverageStatus: 'Juizados Especiais Federais - Temas Representativos da Controvérsia',
    verificationMethod: 'HUMAN_VERIFICATION_LINK',
    termsStatus: 'MANUAL_ONLY',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  },
  {
    sourceId: 'tcu-jurisprudencia',
    name: 'Tribunal de Contas da União - Pesquisa Selecionada & Súmulas',
    courtCode: 'TCU',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://pesquisa.apps.tcu.gov.br/',
    documentationUrl: 'https://portal.tcu.gov.br/jurisprudencia/',
    connectorStatus: 'MANUAL_ONLY',
    coverageStatus: 'Direito Administrativo e Controle Externo - Link oficial para conferência',
    verificationMethod: 'HUMAN_VERIFICATION_LINK',
    termsStatus: 'MANUAL_ONLY',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  },
  {
    sourceId: 'carf-jurisprudencia',
    name: 'Conselho Administrativo de Recursos Fiscais (CARF)',
    courtCode: 'CARF',
    jurisdiction: 'BRASIL',
    sourceType: 'OFFICIAL_SEARCH',
    officialBaseUrl: 'https://carf.fazenda.gov.br/sincon/',
    documentationUrl: 'https://carf.fazenda.gov.br/',
    connectorStatus: 'MANUAL_ONLY',
    coverageStatus: 'Contencioso Administrativo Tributário Federal',
    verificationMethod: 'HUMAN_VERIFICATION_LINK',
    termsStatus: 'MANUAL_ONLY',
    documentsDiscovered: 0,
    documentsFetched: 0,
    documentsValidated: 0,
    documentsRejected: 0,
    enabled: true,
    requiresCredential: false,
    credentialConfigured: false,
  },
];
